# Service exposing nginx either as NodePort or LoadBalancer.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lingua-app.fullname" . }}-nginx-service
  namespace: {{ .Values.namespace.name }}
  labels:
{{ include "lingua-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  selector:
{{ include "lingua-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.port }}
      {{- if eq .Values.nginx.service.type "NodePort" }}
      nodePort: {{ .Values.nginx.service.nodePort }}
      {{- end }}
  type: {{ .Values.nginx.service.type }}
