{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: energy-drain-app

  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}

  endpoints:
    - port: http
      path: {{ .Values.monitoring.path }}
      interval: {{ .Values.monitoring.interval }}

{{- end }}