# Internal Service for the backend Deployment.
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.namespace.name }}
  labels:
{{ include "lingua-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
{{ include "lingua-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  type: ClusterIP
