# Deployment for the backend application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: lingua-app
  labels:
    app: backend
spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: lingua-backend:1.0.0

          imagePullPolicy: Never

          ports:
            - containerPort: 5000

          env:
            - name: MONGO_URL
              value: "mongodb://host.docker.internal:27017"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "256Mi"
              cpu: "250m"
