apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: energy-drain
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mild-byte/language-learninga-gitops
    targetRevision: local
    path: charts/energy-drain-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: energy-drain
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
