apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.15.0
    helm:
      values: |
        provider:
          name: aws
        aws:
          region: ap-south-1
        domainFilters:
          - volt-app.dev
        policy: upsert-only
        txtOwnerId: energy-drain-production
        sources:
          - ingress
        serviceAccount:
          create: true
          name: external-dns
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::523555653711:role/energy-drain-production-external-dns"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
